# Generated by Django 2.2 on 2022-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='airplane_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arrival_city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
