# Generated by Django 2.2 on 2022-05-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220502_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='airplane_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
